import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      



        <iframe width="560" height="315" src="https://www.youtube.com/embed/wE3svJxtND0" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
      
      
      <h1> Ну что Юра нажми на кнопку     </h1>
      <br/>
      <br/>
      <button>


        <h2 className='vanilka'>
        <Link href='vanilka'> Будут девки давать каждый день </Link>
      </h2>
      
      </button>
      
      
      
    </>
  )
}
